### ISSUE TITLE
how do I make it work with Kotlin

### ISSUE THREAD

**Issue by meoyawn** [yole/jitwatch-intellij#1]
here's what I'm getting with a simple kotlin file

``` kotlin
fun main(args: Array<String>): Unit {
  println(fact(100000))
}

fun fact(what: Long): BigInteger =
    if (what == 0L) {
      BigInteger.ZERO
    } else {
      var p = BigInteger.ONE
      for (i in 1..what) {
        p *= BigInteger.valueOf(i)
      }
      p
    }
```

http://grab.by/RWD2

**Comment by meoyawn** [comment]
I also get this IDE Fatal error

```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 11,4,Idea Thread Group] 2107911981
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2016.2.1#IC-162.1447.26 IDEA, eap:false, os:Mac OS X 10.11.5, java-version:JetBrains s.r.o 1.8.0_76-release-b216,6,main] 564693458
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:138)
    at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:951)
    at com.intellij.openapi.module.impl.ModuleManagerImpl.moduleDependencyComparator(ModuleManagerImpl.java:519)
    at com.intellij.openapi.module.ModuleUtilCore.findModuleForPsiElement(ModuleUtilCore.java:113)
    at ru.yole.jitwatch.JitWatchModelService.loadBytecode(JitWatchModelService.kt:163)
    at ru.yole.jitwatch.JitWatchModelService$loadBytecodeAsync$1.run(JitWatchModelService.kt:154)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by meoyawn** [comment]
sorry, I just didn't have hot methods.

just found this benchmark https://github.com/kostya/benchmarks/tree/master/brainfuck2 and my functions started to get compiled
