### ISSUE TITLE
NoClassDefFoundError when Kotlin not found

### ISSUE THREAD

**Issue by lfrancke** [yole/jitwatch-intellij#3]
When the Kotlin plugin is disabled the plugin fails with a `java.lang.NoClassDefFoundError: org/jetbrains/kotlin/idea/search/SearchUtilKt`. I don't know enough about IntelliJ plugins. Can the Kotlin plugin be a dependency or do you have to package some Kotlin runtime in this one or at least add some documentation?

<details>
 <summary>

Stack Trace</summary>

```
org/jetbrains/kotlin/idea/search/SearchUtilKt
java.lang.NoClassDefFoundError: org/jetbrains/kotlin/idea/search/SearchUtilKt
    at ru.yole.jitwatch.languages.JitWatchJavaSupport.findClass(JitWatchJavaSupport.kt:24)
    at ru.yole.jitwatch.languages.JitWatchJavaSupport.findClass(JitWatchJavaSupport.kt:17)
    at ru.yole.jitwatch.JitWatchModelService.getPsiClass(JitWatchModelService.kt:144)
    at ru.yole.jitwatch.JitWatchModelService.getPsiMember(JitWatchModelService.kt:137)
    at ru.yole.jitwatch.JitWatchModelService$loadLog$2$run$1.invoke(JitWatchModelService.kt:92)
    at ru.yole.jitwatch.JitWatchModelService$loadLog$2$run$1.invoke(JitWatchModelService.kt:84)
    at ru.yole.jitwatch.InlineAnalyzer$InlineJournalVisitor.processParseTag(InlineAnalyzer.kt:87)
    at ru.yole.jitwatch.InlineAnalyzer$InlineJournalVisitor.processParseTag$default(InlineAnalyzer.kt:61)
    at ru.yole.jitwatch.InlineAnalyzer$InlineJournalVisitor.visitTag(InlineAnalyzer.kt:58)
    at org.adoptopenjdk.jitwatch.journal.JournalUtil.visitParseTagsOfLastTask(JournalUtil.java:81)
    at ru.yole.jitwatch.InlineAnalyzer.visit(InlineAnalyzer.kt:47)
    at org.adoptopenjdk.jitwatch.treevisitor.TreeVisitor.walkPackage(TreeVisitor.java:48)
    at org.adoptopenjdk.jitwatch.treevisitor.TreeVisitor.walkPackage(TreeVisitor.java:39)
    at org.adoptopenjdk.jitwatch.treevisitor.TreeVisitor.walkTree(TreeVisitor.java:29)
    at ru.yole.jitwatch.JitWatchModelService$loadLog$2$run$2.run(JitWatchModelService.kt:96)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:856)
    at ru.yole.jitwatch.JitWatchModelService$loadLog$2.run(JitWatchModelService.kt:95)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlin.idea.search.SearchUtilKt PluginClassLoader[ru.yole.jitwatch-intellij, 1.0]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 30 more
```

</details>

**Comment by nitram509** [comment]
Same here.

My environment (I hope this might give some context):
- Mac OSX
- IntelliJ IDEA 2016.2.3. EAP, Build #IU-162.1812.8, built on August 23, 2016
- project setup java jdk1.8.0_92 (Oracle)

**Comment by rbento** [comment]
Same here. Also I had JITWatch installed when I disabled Kotlin plugin and no dependency message was displayed, like for other plugins.

**Comment by stokito** [comment]
The problem still present. I enabled a Kotlin plugin and then occured #7
