### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by tanmatra** [yole/jitwatch-intellij#5]
```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 22,4,Idea Thread Group] 1470409042
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2016.2.2#IU-162.1628.40 IDEA, eap:false, os:Windows 7 6.1, java-version:JetBrains s.r.o 1.8.0_76-release-b218,6,main] 1331135866
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:138)
    at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:951)
    at com.intellij.openapi.module.impl.ModuleManagerImpl.moduleDependencyComparator(ModuleManagerImpl.java:519)
    at com.intellij.openapi.module.ModuleUtilCore.findModuleForPsiElement(ModuleUtilCore.java:113)
    at ru.yole.jitwatch.JitWatchModelService.loadBytecode(JitWatchModelService.kt:163)
    at ru.yole.jitwatch.JitWatchModelService$loadBytecodeAsync$1.run(JitWatchModelService.kt:154)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by httpdigest** [comment]
I'm getting the same exception, plus two more, on IntelliJ IDEA Ultimate 2016.2.4 when loading a jit log file produced by JDK1.8.0_102 on Windows x64:

```
Failed to build annotations: Expected an invoke instruction (in INLINE_SUCCESS) at offset: 0 but was mnemonic: Unknown
org.adoptopenjdk.jitwatch.model.AnnotationException: Expected an invoke instruction (in INLINE_SUCCESS) at offset: 0 but was mnemonic: Unknown
    at org.adoptopenjdk.jitwatch.model.bytecode.BytecodeAnnotationBuilder.buildParseTagAnnotations(BytecodeAnnotationBuilder.java:442)
    at org.adoptopenjdk.jitwatch.model.bytecode.BytecodeAnnotationBuilder.visitTagParse(BytecodeAnnotationBuilder.java:181)
    at org.adoptopenjdk.jitwatch.model.bytecode.BytecodeAnnotationBuilder.visitTag(BytecodeAnnotationBuilder.java:156)
    at org.adoptopenjdk.jitwatch.journal.JournalUtil.visitParseTagsOfLastTask(JournalUtil.java:81)
    at org.adoptopenjdk.jitwatch.model.bytecode.BytecodeAnnotationBuilder.buildParseTagAnnotations(BytecodeAnnotationBuilder.java:135)
    at org.adoptopenjdk.jitwatch.model.bytecode.BytecodeAnnotationBuilder.buildBytecodeAnnotations(BytecodeAnnotationBuilder.java:109)
    at ru.yole.jitwatch.JitWatchModelService.buildAllBytecodeAnnotations(JitWatchModelService.kt:191)
    at ru.yole.jitwatch.JitWatchModelService.loadBytecode(JitWatchModelService.kt:173)
    at ru.yole.jitwatch.JitWatchModelService$loadBytecodeAsync$1.run(JitWatchModelService.kt:154)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)


org.adoptopenjdk.jitwatch.model.AnnotationException: Expected a branch instruction (BRANCH) at offset: 3 but was mnemonic: Unknown
    at org.adoptopenjdk.jitwatch.model.bytecode.BytecodeAnnotationBuilder.buildParseTagAnnotations(BytecodeAnnotationBuilder.java:478)
    at org.adoptopenjdk.jitwatch.model.bytecode.BytecodeAnnotationBuilder.visitTagParse(BytecodeAnnotationBuilder.java:181)
    at org.adoptopenjdk.jitwatch.model.bytecode.BytecodeAnnotationBuilder.visitTag(BytecodeAnnotationBuilder.java:156)
    at org.adoptopenjdk.jitwatch.journal.JournalUtil.visitParseTagsOfLastTask(JournalUtil.java:81)
    at org.adoptopenjdk.jitwatch.model.bytecode.BytecodeAnnotationBuilder.buildParseTagAnnotations(BytecodeAnnotationBuilder.java:135)
    at org.adoptopenjdk.jitwatch.model.bytecode.BytecodeAnnotationBuilder.buildBytecodeAnnotations(BytecodeAnnotationBuilder.java:109)
    at ru.yole.jitwatch.JitWatchModelService.buildAllBytecodeAnnotations(JitWatchModelService.kt:191)
    at ru.yole.jitwatch.JitWatchModelService.loadBytecode(JitWatchModelService.kt:173)
    at ru.yole.jitwatch.JitWatchModelService$loadBytecodeAsync$1.run(JitWatchModelService.kt:154)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```
