### ISSUE TITLE
Already disposed

### ISSUE THREAD

**Issue by krasa** [yole/jitwatch-intellij#6]
```
Already disposed: Project (Disposed) testHibernate
java.lang.AssertionError: Already disposed: Project (Disposed) testHibernate
    at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:171)
    at com.intellij.openapi.wm.ToolWindowManager.getInstance(ToolWindowManager.java:37)
    at ru.yole.jitwatch.JitActionsKt.registerToolWindows(JitActions.kt:49)
    at ru.yole.jitwatch.JitActionsKt.loadLogAndShowUI(JitActions.kt:32)
    at ru.yole.jitwatch.JitRunConfigurationExtension$attachToProcess$1$processTerminated$1.run(JitRunConfigurationExtension.kt:90)
    at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:294)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:334)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:318)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:831)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:667)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by nanashj** [comment]
[_****_]()

**Comment by nanashj** [comment]
> ```
> Already disposed: Project (Disposed) testHibernate
> java.lang.AssertionError: Already disposed: Project (Disposed) testHibernate
>     at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:171)
>     at com.intellij.openapi.wm.ToolWindowManager.getInstance(ToolWindowManager.java:37)
>     at ru.yole.jitwatch.JitActionsKt.registerToolWindows(JitActions.kt:49)
>     at ru.yole.jitwatch.JitActionsKt.loadLogAndShowUI(JitActions.kt:32)
>     at ru.yole.jitwatch.JitRunConfigurationExtension$attachToProcess$1$processTerminated$1.run(JitRunConfigurationExtension.kt:90)
>     at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:294)
>     at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:334)
>     at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:318)
>     at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
>     at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
>     at java.awt.EventQueue.access$500(EventQueue.java:97)
>     at java.awt.EventQueue$3.run(EventQueue.java:709)
>     at java.awt.EventQueue$3.run(EventQueue.java:703)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
>     at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
>     at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:831)
>     at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:667)
>     at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
>     at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
>     at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
>     at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
>     at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> ```
>

**Comment by nanashj** [comment]
320920
